_core:
  default_config_hash: QDFjOXYIYVwCPQYHY4wAx4DUqOEkNaZokIx6DGApR9I
enable_globally: 1
enable_globally_on_admin_routes: false
default_challenge: image_captcha/Image
description: ''
title: CAPTCHA
administration_mode: false
administration_mode_on_admin_routes: false
whitelist_ips: 192.168.1.107
wrong_captcha_response_message: 'The answer you entered for the CAPTCHA was not correct.'
default_validation: 1
persistence: 1
enable_stats: false
log_wrong_responses: true
